### PR TITLE
[debug] fixed adam & softmax

### PR DESCRIPTION
**Pull request by fufjvnvnf**
hello

### CODE REVIEW

**Comment by fufjvnvnf** [comment]
mnist now runnable; partly fixed adam; runnable yet producing NaN

**Comment by stevenygd** [comment]
1. Please check out your changes in examples if that's not important.
2. Please check out or delete your file `mnist_conv_test.jl` since that's probably not relevant.
Other things all look good.

**Comment by fufjvnvnf** [comment]
deleting them once adam is fixed

**Comment by fufjvnvnf** [comment]
Read for merge

**Pull request closed without merging**
