### PR TITLE
add numerical stability line

### PR DESCRIPTION
**Pull request by Tiiiger**
Add numerical stability according to http://cs231n.github.io/linear-classify/#softmax.

### CODE REVIEW

**Comment by fufjvnvnf** [comment]
Provide differences in benchmark test please.

**Comment by stevenygd** [comment]
@fufjvnvnf I guess the test should be the one with extremely big or small number. i.e. try to have an array in the scale of `e^6`, [1e^100, 1.1e^100, 1.2e^100] and they should still be able to compute the softmax.

**Comment by stevenygd** [comment]
@Tiiiger Maybe `e^6` is not realistic, but this test from http://cs231n.github.io/linear-classify/#softmax look reasonable:
```python
f = np.array([123, 456, 789]) # example with 3 classes and each having large scores
p = np.exp(f) / np.sum(np.exp(f)) # Bad: Numeric problem, potential blowup

# instead: first shift the values of f so that the highest number is 0:
f -= np.max(f) # f becomes [-666, -333, 0]
p = np.exp(f) / np.sum(np.exp(f)) # safe to do, gives the correct answer

```

**Comment by stevenygd** [comment]
https://github.com/stevenygd/NN.jl/issues/19

**Pull request merged**
